repos:
  - repo: local
    hooks:
      - id: just-all
        name: just-all
        entry: just build
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false