repos:
  - repo: local
    hooks:
      - id: just-all
        name: just-all
        entry: just build
        language: system
        types: [rust]
      - id: build
        name: build
        description: Format files with cargo fmt.
        entry: cargo build
        language: system
        types: [rust]
        args: ["--"]