repos:
  - repo: local
    hooks:
      - id: just-all
        name: just-all
        entry: just all
        verbose: true
        language: system
        types: [rust]
        stages: [post-commit]
        pass_filenames: false
