[package]
name = "cw-rules-core"
description = "CronCat rules logic for tasks that require conditions"
license = "MIT OR Apache-2.0"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
cosmwasm-std = { version = "1.0.0", features = ["staking", "stargate"] }
serde-cw-value = "0.7.0"
# For some reason it tries to deploy cw_core here
# voting = { version = "0.2.0", default-features = false, git = "https://github.com/DA0-DA0/dao-contracts" }
generic-query = { version = "0.1.1", path = "../generic-query" }
smart-query = { version = "0.1.0", path = "../smart-query" }
cw20 = { version = "0.13.4" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
