[package]
name = "croncat-sdk-tasks"
version = "0.1.0"
authors = []
edition = "2021"
repository = "https://github.com/CronCats/cw-croncat"

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw20 = { workspace = true }
cron_schedule = { workspace = true }

croncat-mod-generic = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
