[package]
name = "cw-croncat-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "1.0.0-beta6", features = ["staking", "stargate"] }
cosmwasm-storage = { version = "1.0.0-beta6" }
cw-storage-plus = "0.13"
cron_schedule = "0.2.0"
cw2 = "0.13"
cw20 = { version = "0.12.1" }
cw20-base = { version = "0.12.1", features = ["library"] }
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
hex = "0.4"
sha2 = "0.9"

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta6" }
cw-multi-test = { version = "0.13", features = ["staking"] }
cw20-base = { version = "0.12.1", features = ["library"] }
