[package]
name = "generic-query"
version = "0.1.0"
edition = "2021"

[dependencies]
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
cosmwasm-std = { version = "1.0.0", features = ["staking", "stargate"] }
serde-cw-value = "0.7.0"
